/******************************************************************************/
/***               Generated by IBExpert 17.05.2025 12:11:18                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;




CREATE TRIGGER EVENTS_PARKING_HL FOR EVENTS
ACTIVE AFTER INSERT POSITION 0
AS
  DECLARE VARIABLE pID int;
  DECLARE VARIABLE IsEnter int;


begin
  /* Событие должно быть "действительная карта" и должен присутствовать ид пользователя*/
  if (new.id_eventtype = 50 and new.ess1 IS NOT NULL) then begin
    /* ищем, соответствует ли точке прохода какая-нибудь парковка */

        select hlp.id_parking, hlp.is_enter from  hl_param hlp
            where hlp.id_dev=new.id_dev into :pID, :IsEnter;

     DELETE FROM hl_inside  WHERE counterid = :pID and id_pep = new.ess1;

    if (pID IS NOT NULL) then begin   /* парковка найдена */
      if (IsEnter = 0) then begin     /* это выезд */

       -- DELETE FROM hl_inside  WHERE id_pep = new.ess1;
      end else begin                  /* это въезд */
        -- удаляем запись о нахождении внутри (если она есть) в любом случае

        -- а записываем только тех, у кого есть снимаемая категория

      INSERT INTO HL_inside  (ENTERTIME, id_card, id_pep, counterid) VALUES (new.datetime, new.id_card, new.ess1, :pID );
      end
    end
  end
end
^


SET TERM ; ^
