/******************************************************************************/
/***               Generated by IBExpert 31.03.2025 12:03:41                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_HL_EVENTS_ID;

CREATE TABLE HL_EVENTS (
    ID          INTEGER NOT NULL,
    EVENT_CODE  INTEGER NOT NULL,
    EVENT_TIME  TIMESTAMP DEFAULT 'Now' NOT NULL,
    IS_ENTER    INTEGER,
    RUBI_CARD   VARCHAR(10),
    PARK_CARD   VARCHAR(10),
    GRZ         VARCHAR(12),
    COMMENT     VARCHAR(255),
    PHOTO       BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    ID_PEP      INTEGER,
    ID_GATE     INTEGER,
    CREATED     TIMESTAMP DEFAULT 'now'
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_EVENTS ADD CONSTRAINT PK_HL_EVENTS PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_EVENTS ADD CONSTRAINT FK_HL_EVENTS_1 FOREIGN KEY (EVENT_CODE) REFERENCES HL_EVENTCODE (ID) ON DELETE CASCADE;


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: HL_EVENTS_BI */
CREATE TRIGGER HL_EVENTS_BI FOR HL_EVENTS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_HL_EVENTS_ID,1);
END
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of procedures */
GRANT INSERT ON HL_EVENTS TO PROCEDURE REGISTERPASS_HL_2;


