/******************************************************************************/
/***               Generated by IBExpert 31.03.2025 12:08:14                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_HL_GARAGENAME_ID;

CREATE TABLE HL_GARAGENAME (
    ID         INTEGER NOT NULL,
    NAME       STR_250 /* STR_250 = VARCHAR(250) */,
    CREATED    TIMESTAMP DEFAULT 'now',
    NOT_COUNT  INTEGER DEFAULT 0,
    DIV_CODE   STR_50 NOT NULL /* STR_50 = VARCHAR(50) */
);




/******************************************************************************/
/***                           Unique Constraints                           ***/
/******************************************************************************/

ALTER TABLE HL_GARAGENAME ADD CONSTRAINT UNQ1_HL_GARAGENAME UNIQUE (DIV_CODE);


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_GARAGENAME ADD CONSTRAINT PK_HL_GARAGENAME PRIMARY KEY (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: HL_GARAGENAME_BI */
CREATE TRIGGER HL_GARAGENAME_BI FOR HL_GARAGENAME
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_HL_GARAGENAME_ID,1);
   if (new.div_code is null) then
   new.div_code='garage_'||new.id  ;
END
^


SET TERM ; ^



/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

DESCRIBE TABLE HL_GARAGENAME
'Перечень гаражей';



/* Fields descriptions */

DESCRIBE FIELD DIV_CODE TABLE HL_GARAGENAME
'Уникальное обозначение для интеграции.';

DESCRIBE FIELD NAME TABLE HL_GARAGENAME
'Название гаража
';

DESCRIBE FIELD NOT_COUNT TABLE HL_GARAGENAME
'Признак НЕ считать количество свободных мест в гараже.';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
