/******************************************************************************/
/***               Generated by IBExpert 06.05.2025 19:33:23                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE HL_INSIDE (
    ENTERTIME  TIMESTAMP DEFAULT 'now' NOT NULL,
    ID_CARD    VARCHAR(32) NOT NULL,
    ID_PEP     INTEGER NOT NULL,
    COUNTERID  INTEGER NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_INSIDE ADD CONSTRAINT PK_HL_INSIDE PRIMARY KEY (ID_PEP);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of procedures */
GRANT SELECT, DELETE ON HL_INSIDE TO PROCEDURE REGISTERPASS_HL_2;
GRANT SELECT ON HL_INSIDE TO PROCEDURE VALIDATEPASS_HL_PARKING;
GRANT SELECT ON HL_INSIDE TO PROCEDURE VALIDATEPASS_HL_PARKING_2;
GRANT SELECT ON HL_INSIDE TO PROCEDURE VALIDATEPASS_HL_PARKING_3;