/******************************************************************************/
/***               Generated by IBExpert 31.03.2025 12:10:25                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE HL_MESSAGES (
    ID           INTEGER,
    EVENTCODE    INTEGER,
    TEXT         VARCHAR(250),
    PARAM        VARCHAR(250),
    "TIMESTAMP"  TIMESTAMP DEFAULT 'now',
    SMALNAME     VARCHAR(10)
);




/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

DESCRIBE TABLE HL_MESSAGES
'Таблица HL_MESSAGES предназначена для хранения сообщений, выводимых на средства отображения информации (табло или иные приборы)';



/* Fields descriptions */

DESCRIBE FIELD EVENTCODE TABLE HL_MESSAGES
'Ссылка на код события, связанного с этим сообщением.';

DESCRIBE FIELD PARAM TABLE HL_MESSAGES
'Параметры текста в строковом виде (начальные координакты, цвет и т.п.)';

DESCRIBE FIELD SMALNAME TABLE HL_MESSAGES
'Краткое название сообщения. Например alarm, time и т.п.';

DESCRIBE FIELD TEXT TABLE HL_MESSAGES
'Текст, выводимый на табло';

DESCRIBE FIELD "TIMESTAMP" TABLE HL_MESSAGES
'Метка времени создания или последного обновления';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
commit;
INSERT INTO HL_MESSAGES (ID, EVENTCODE, TEXT, PARAM, "TIMESTAMP", SMALNAME) VALUES (NULL, 46, 'Проезд запрещен. Неизвестная карта.', '{"dx":"0","dy":"8","messColor":"4","messScroll":"1"}', NULL, NULL);
INSERT INTO HL_MESSAGES (ID, EVENTCODE, TEXT, PARAM, "TIMESTAMP", SMALNAME) VALUES (NULL, 50, 'Добро пожаловать!', '{"dx":"0","dy":"8","messColor":"2","messScroll":"1"}', '2023-04-07 12:31:47', NULL);
INSERT INTO HL_MESSAGES (ID, EVENTCODE, TEXT, PARAM, "TIMESTAMP", SMALNAME) VALUES (NULL, 65, 'Проезд запрещен. Нет прав.', '{"dx":"0","dy":"8","messColor":"1","messScroll":"1"}', '2023-04-07 12:32:18', NULL);
INSERT INTO HL_MESSAGES (ID, EVENTCODE, TEXT, PARAM, "TIMESTAMP", SMALNAME) VALUES (NULL, 81, 'Проезд запрещен. Нет мест.', '{"dx":"0","dy":"8","messColor":"6","messScroll":"1"}', '2023-04-07 12:32:46', NULL);
INSERT INTO HL_MESSAGES (ID, EVENTCODE, TEXT, PARAM, "TIMESTAMP", SMALNAME) VALUES (NULL, NULL, 'Паркинг', '{"dx":31,"dy":32,"messColor":33,"messScroll":34}', '2023-04-07 12:33:54', 'text1');
INSERT INTO HL_MESSAGES (ID, EVENTCODE, TEXT, PARAM, "TIMESTAMP", SMALNAME) VALUES (NULL, NULL, 'Шмитовский, 39', '{"dx":41,"dy":42,"messColor":43,"messScroll":44}', '2023-04-07 12:34:14', 'text2');