/******************************************************************************/
/***               Generated by IBExpert 31.03.2025 12:12:06                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_HL_ORGACCESS_ID;

CREATE TABLE HL_ORGACCESS (
    ID         INTEGER NOT NULL,
    ID_ORG     INTEGER,
    ID_GARAGE  INTEGER,
    IS_ACTIVE  INTEGER DEFAULT 1,
    CREATED    TIMESTAMP DEFAULT 'now'
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_ORGACCESS ADD CONSTRAINT PK_HL_ORGACCESS PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_ORGACCESS ADD CONSTRAINT FK_HL_ORGACCESS_1 FOREIGN KEY (ID_GARAGE) REFERENCES HL_GARAGENAME (ID) ON DELETE CASCADE;
ALTER TABLE HL_ORGACCESS ADD CONSTRAINT FK_HL_ORGACCESS_2 FOREIGN KEY (ID_ORG) REFERENCES ORGANIZATION (ID_ORG) ON DELETE CASCADE;


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: HL_ORGACCESS_BI */
CREATE TRIGGER HL_ORGACCESS_BI FOR HL_ORGACCESS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_hl_orgaccess_id,1);
end
^


SET TERM ; ^



/* Fields descriptions */

DESCRIBE FIELD ID_GARAGE TABLE HL_ORGACCESS
'На какие парковки может заезжать представитель организации';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of procedures */
GRANT SELECT ON HL_ORGACCESS TO PROCEDURE VALIDATEPASS_HL_PARKING_2;
GRANT SELECT ON HL_ORGACCESS TO PROCEDURE VALIDATEPASS_HL_PARKING_3;