/******************************************************************************/
/***               Generated by IBExpert 31.03.2025 12:14:58                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_HL_PLACE_ID;

CREATE TABLE HL_PLACE (
    ID           INTEGER NOT NULL,
    PLACENUMBER  INTEGER,
    ID_COUNTERS  INTEGER,
    DESCRIPTION  STR_250 /* STR_250 = VARCHAR(250) */,
    NOTE         STR_250 /* STR_250 = VARCHAR(250) */,
    STATUS       INTEGER,
    NAME         STR_100 /* STR_100 = VARCHAR(100) */,
    ID_PARKING   SMALLINT,
    CREATED      TIMESTAMP DEFAULT 'now'
);




/******************************************************************************/
/***                           Unique Constraints                           ***/
/******************************************************************************/

ALTER TABLE HL_PLACE ADD CONSTRAINT UNQ1_HL_PLACE UNIQUE (PLACENUMBER, ID_PARKING);


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_PLACE ADD CONSTRAINT PK_HL_PLACE PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_PLACE ADD CONSTRAINT FK_HL_PLACE_1 FOREIGN KEY (ID_PARKING) REFERENCES HL_PARKING (ID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX HL_PLACE_IDX1 ON HL_PLACE (ID_PARKING);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: HL_PLACE_BI */
CREATE TRIGGER HL_PLACE_BI FOR HL_PLACE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_HL_PLACE_ID,1);
END
^


SET TERM ; ^



/* Fields descriptions */

DESCRIBE FIELD DESCRIPTION TABLE HL_PLACE
'Описание мишиноместа.';

DESCRIBE FIELD ID_COUNTERS TABLE HL_PLACE
'Совпадает с ID_PARKING. Поле оставлено для совместимости на период отладки.';

DESCRIBE FIELD ID_PARKING TABLE HL_PLACE
'Ссылка на парковку, к которой "привязано" машиноместо.';

DESCRIBE FIELD NAME TABLE HL_PLACE
'Название машиноместа. Название может отличаться от номера. Например, В-21.';

DESCRIBE FIELD NOTE TABLE HL_PLACE
'Заметки по машиноместу.';

DESCRIBE FIELD PLACENUMBER TABLE HL_PLACE
'Порядковый номер машиноместа.';

DESCRIBE FIELD STATUS TABLE HL_PLACE
'Статус.
0 - рабочее состояние
1 - использование запрещено.
Возможны другие варианты.
Пока не используется.';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of procedures */
GRANT SELECT ON HL_PLACE TO PROCEDURE VALIDATEPASS_HL_PARKING_3;