/******************************************************************************/
/***                Generated by IBExpert 10.04.2025 8:51:16                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_HL_PARKING_ID;

CREATE TABLE HL_PARKING (
    ID        INTEGER NOT NULL,
    NAME      STR_50 NOT NULL /* STR_50 = VARCHAR(50) */,
    ENABLED   INTEGER DEFAULT 1 NOT NULL,
    CREATED   TIMESTAMP DEFAULT 'now',
    MAXCOUNT  INTEGER,
    PARENT    INTEGER,
    MODIFY    TIMESTAMP
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_PARKING ADD CONSTRAINT PK_HL_PARKING PRIMARY KEY (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: HL_PARKING_AU0 */
CREATE TRIGGER HL_PARKING_AU0 FOR HL_PARKING
ACTIVE AFTER UPDATE POSITION 0
AS
begin
  if((new.name <> old.name) or (new.enabled <> old.enabled))  then
    update hl_parking set modify='now' where id=old.id;

end
^

/* Trigger: HL_PARKING_BI */
CREATE TRIGGER HL_PARKING_BI FOR HL_PARKING
ACTIVE BEFORE INSERT POSITION 0
as
            begin
              if (new.id is null) then
                new.id = gen_id(gen_hl_parking_id,1);
            end
^

/* Trigger: HL_PARKING_BI0 */
CREATE TRIGGER HL_PARKING_BI0 FOR HL_PARKING
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if(new.enabled is null) then new.enabled=1;
end
^

/* Trigger: HL_PARKING_SET_CREATED */
CREATE TRIGGER HL_PARKING_SET_CREATED FOR HL_PARKING
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if(NEW.created is null)  then
        NEW.created='now';
end
^


SET TERM ; ^

commit;

/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

Update Rdb$Relations set Rdb$Description =
'Перечень парковочноых комплексов (parent=0)
и перечень парковок, входяищ в комплекс (parent>0)'
where Rdb$Relation_Name='HL_PARKING';

Update Rdb$Relation_Fields set Rdb$Description =
'Количество мест на парковке согласно проектной документации'
where Rdb$Relation_Name='HL_PARKING' and Rdb$Field_Name='MAXCOUNT';

Update Rdb$Relation_Fields set Rdb$Description =
'Родительская парковка'
where Rdb$Relation_Name='HL_PARKING' and Rdb$Field_Name='PARENT';